### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mathieuboudreau** [sunhongfu/QSM#1]
Hi Hongfu!

You omitted a license file in your repo. I was wondering if you meant for this code to be available for use and reuse, like the [MIT license provides](https://tldrlegal.com/license/mit-license), or if you meant to reserve all rights, like [what happens by default when no license file is given](https://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github).

Cheers!

Mathieu

**Comment by sunhongfu** [comment]
Hi Mathieu,
Thanks for pointing this out. Anyone can use and reuse the code, so I should probably add a MIT license to make this clear!

Hongfu

**Comment by mathieuboudreau** [comment]
Thanks for clarifying @sunhongfu!
